## Deployment
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: seo-eks-app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: seo-eks-app
  template:
    metadata:
      labels:
        app: seo-eks-app
    spec:
      containers:
      - name: seo-eks-app
        image: 317396387403.dkr.ecr.us-east-1.amazonaws.com/jenkins-job:V14
        imagePullPolicy: Always
        ports:
        - containerPort: 8082
# service type loadbalancer       
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: seo-eks-app
    k8s-app: seo-eks-app
  name: seo-eks-app
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8082
  type: LoadBalancer
  selector:
    app: seo-eks-app
